import json
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()


def generate_clip_plan_json(prompt: str, target_duration_s: int) -> str:
    """
    Image-based planner (trial contract):
    - Total duration fixed to 20 seconds
    - The 20s explainer is broken into multiple image-based frames
    - Each frame becomes:
        * one generated still image (text-to-image)
        * one short animated segment derived from that still (ffmpeg)
    - No narration/audio
    """

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not found in .env")

    client = OpenAI(api_key=api_key)
    model = (os.getenv("OPENAI_MODEL") or "gpt-5.2-chat-latest").strip()

    system_prompt = (
        "You are a professional storyboard artist and academic explainer-video designer. "
        "You design sophisticated educational visuals for university-level content, explaining advanced concepts "
        "with professional, cinematic quality suitable for higher education. "
        "Return ONLY valid JSON. No markdown. No explanations. No extra text."
    )

    user_prompt = f"""
Design a 20-second ACADEMIC EXPLAINER plan for university-level students that will be produced using
IMAGE-BASED ANIMATION (not direct text-to-video), for the following advanced topic:

TOPIC:
\"\"\"{prompt}\"\"\"

AUDIENCE: University students studying advanced concepts. The visual style must be:
- Professional, sophisticated, and academically rigorous
- Cinematic quality suitable for higher education
- Clean, modern, and visually engaging without being childish or cartoonish
- Appropriate for explaining complex, technical, or abstract concepts

CRITICAL: ENVIRONMENT REALISM (MOST IMPORTANT FOR VISUAL QUALITY):
- ANALYZE THE TOPIC to determine if it's a REAL-WORLD/PHYSICAL topic or ABSTRACT/THEORETICAL topic.
- For REAL-WORLD/PHYSICAL topics (e.g., airplanes, biology, chemistry, engineering, physics of everyday objects, natural phenomena):
  * Use PHOTOREALISTIC, REALISTIC ENVIRONMENTS - show real objects in their natural settings
  * Examples: Real commercial airplane flying in blue sky with clouds, real plants in natural environment, real chemical reactions in lab glassware, real mechanical systems in industrial settings
  * NO wind tunnels, NO digital/synthetic environments, NO abstract backgrounds unless the topic specifically requires it
  * The environment should be what you would see in real life: sky for airplanes, ocean for marine biology, lab for chemistry, etc.
- For ABSTRACT/THEORETICAL topics (e.g., quantum mechanics, pure mathematics, theoretical physics, abstract concepts):
  * Use APPROPRIATE ABSTRACT/DIGITAL ENVIRONMENTS - can be stylized, digital, or abstract visualizations
  * Examples: Abstract quantum field visualizations, mathematical graph spaces, theoretical particle interactions, digital/synthetic environments
  * These can include stylized backgrounds, abstract visualizations, or digital environments that help explain the concept
- The environment_details field MUST reflect the chosen environment type (realistic for real-world, abstract for theoretical)
- ALL image_prompt descriptions MUST describe the environment as realistic (for physical topics) or appropriately abstract (for theoretical topics)

PIPELINE (for your awareness):
- Step 1: Your plan becomes a 20-second MASTER SCRIPT that will be followed for the whole video. The script is split into a sequence of SEGMENTS (frames), each with its own narration and visual description.
- Step 2: ONLY THE FIRST FRAME is generated as a still image via text-to-image (Nano Banana). This image is the first frame of the first video segment. Items inside this image will be moved or animated.
- Step 3: The first image is animated using image-to-video (I2V): items inside move/animate → first video segment. The LAST FRAME of this first video becomes the input for the second video.
- Step 4: The second video is generated by I2V using the last frame of the first video as its first frame. The last frame of the second video becomes the input for the third. This chaining continues for all segments.
- Step 5: Narration audio is generated for each segment and synced with the video.
- Step 6: All segments are concatenated into one final video that follows LONG-TAKE CINEMATOGRAPHY: continuous movement, no visible cuts, long takes, real-time feeling, camera choreography.

CRITICAL: LONG-TAKE CINEMATOGRAPHY (MOST IMPORTANT):
- The final video must feel like ONE CONTINUOUS SHOT: long-take cinematography with continuous movement, NO visible cuts, long takes, real-time feeling, and deliberate camera choreography.
- Each segment CONTINUES directly from where the previous segment ended. The input image for segment N+1 is the last frame of segment N — so there are no jumps or cuts between segments.
- Use continuous camera movements: dolly, pan, orbit, crane, tracking shots, push-in, pull-out. The camera choreography should feel planned and smooth across all segments.
- Elements/objects must maintain spatial and visual consistency as the camera moves. What appears at the end of segment N is exactly what segment N+1 starts from.
- Think of this as a single Steadicam or gimbal shot: the camera moves smoothly through space, never cutting. Real-time feeling: the viewer experiences one unbroken take.
- The style_bible.camera_rules MUST define ONE continuous camera movement pattern that applies across all segments (e.g., "slow dolly forward while panning left, then orbit around subject, maintaining smooth choreography throughout").

HARD CONSTRAINTS (must follow exactly):
- Total video duration MUST be 20 seconds.
- The sum of all frame duration_s MUST be exactly 20.
- Use between 5 and 10 frames in total (inclusive).
- Output MUST be valid JSON only. No markdown. No comments. No extra keys beyond the schema.
- JSON must use double quotes for all keys/strings. No trailing commas.
- NO humans may appear on screen: no people, no faces, no hands, no silhouettes, no cockpit interior.
- NO logos/brands/watermarks.

ACADEMIC PRESENTATION STRATEGY (must be used):
- Explain using sophisticated, professional visuals + on-screen text overlays + deliberate pacing.
- Visual style: Professional, clean, modern, cinematic. Think documentary/science channel quality, not cartoon or children's animation.
- On-screen text overlays MUST be:
  - concise and academically appropriate (3–7 words, technical terms allowed)
  - professional typography, high-contrast, highly readable
  - placed where they do NOT cover the main subject
  - styled appropriately for university-level content (e.g., sans-serif modern fonts, not playful fonts)

FRAME STRUCTURE (script segments for long-take chaining):
- The script is split into SEGMENTS. Only the FIRST segment's image is generated by T2I; all later segments get their first frame from the last frame of the previous segment.
- Frame 1 image_prompt: This is the ONLY image generated by text-to-image. Describe the opening scene with DETAILED OBJECT/ITEM DESCRIPTIONS so that items can be animated (moved) within the image. Include elements that naturally move: arrows, particles, fluids, rotating parts, etc.
- Frames 2, 3, ... image_prompt: Describe what this segment should SHOW and how it continues from the previous segment. The I2V model will receive the previous segment's last frame as input; your description guides how the scene should animate and evolve (camera movement, object motion, continuity).
- For each frame, you MUST explicitly describe:
  - duration_s: how long this segment lasts (integer seconds, 1–5 typical, can be less than 2 seconds or more).
  - image_prompt: CRITICAL - For frame 1: full scene description with objects/items and spatial relationships (this is the only T2I image). For frames 2+: describe the scene and action for this segment so that I2V can continue from the previous last frame; include object positions, movements, and how the camera continues.
  - animation_type: How the camera moves in this segment (use same or smooth progression for long-take feel): "hold", "ken_burns_zoom_in", "ken_burns_zoom_out", "pan_left", "pan_right", "pan_up", "pan_down".
  - on_screen_text_overlay: short text or "none".
  - narration_text: Narration to be spoken during this segment. Explain the CONCEPT, not the visuals. Match duration (approx. 2.5-3 words per second). Academic language for university students.
  - continuity_note: CRITICAL for long-take - Describe how this segment continues from the previous: where the camera was, where it moves to, which elements stay consistent, which move or evolve. For frame 1, describe how the opening leads into the next segment.
  - transition_to_next_frame: How this segment leads into the next (camera movement, object movements, final state). For the last frame, describe a natural conclusion.
  - environment_details: 1–4 concrete environmental details. CONSISTENT across segments (same environment). REALISTIC for real-world topics, APPROPRIATELY ABSTRACT for theoretical topics.

MOTION AND LAYOUT RULES (very important):
- Every image_prompt must include ELEMENTS THAT CAN ANIMATE: arrows that slide, particles that move, fluids that flow, rotating gears, sliding panels, changing numbers/values, etc.
- Describe elements with their intended motion: "arrow pointing right and sliding left to right", "water droplets falling", "particles flowing upward", "rotating wheel", "number increasing from 0 to 100".
- The image-to-video AI will animate these elements naturally, so describe them in a way that suggests their motion.
- animation_type provides overall camera movement context, but the real animation comes from elements moving within the image.
- CRITICAL: All frames must use the SAME animation_type (or a smooth progression) to maintain the one-take effect.

ALLOWED animation_type VALUES (choose ONE and use consistently, or use a smooth progression):
- "hold" (static camera, subtle micro-movements)
- "ken_burns_zoom_in" (continuous slow zoom in)
- "ken_burns_zoom_out" (continuous slow zoom out)
- "pan_left" (continuous slow pan left)
- "pan_right" (continuous slow pan right)
- "pan_up" (continuous slow pan up)
- "pan_down" (continuous slow pan down)

OUTPUT JSON STRUCTURE (must match exactly):
{{
  "style_bible": {{
    "visual_style": "Professional, sophisticated, cinematic quality suitable for university-level academic content. Clean, modern, visually engaging. Think documentary/science channel aesthetic, not cartoon or children's animation. For REAL-WORLD topics: photorealistic, realistic environments showing real objects in natural settings. For ABSTRACT topics: appropriately stylized or digital environments that aid conceptual understanding.",
    "camera_rules": "ONE CONTINUOUS CAMERA MOVE: [describe the single camera movement pattern that applies to ALL frames, e.g., 'slow dolly left-to-right at 35mm lens, maintaining consistent framing and speed throughout all 20 seconds']",
    "lighting_rules": "Professional, cinematic lighting appropriate for academic/educational content. Clean, clear, well-lit to show technical details clearly.",
    "continuity_rules": "All frames are keyframes from the same continuous shot. Camera never cuts or jumps. Elements maintain spatial relationships as camera moves smoothly along one path."
  }},
  "full_script_20s": ".",
  "frames": [
    {{
      "frame_id": 1,
      "duration_s": 3,
      "image_prompt": ".",
      "animation_type": "[USE THE SAME animation_type FOR ALL FRAMES, or a smooth progression]",
      "on_screen_text_overlay": "none",
      "narration_text": "Concise narration text for this segment, matching the duration_s (approximately 2.5-3 words per second).",
      "transition_to_next_frame": "Describe how this frame transitions to frame 2. Camera movement: [how camera moves]. Object movements: [how objects move]. Final state: [should match frame 2's description].",
      "environment_details": ["...", "..."],
      "lighting": ".",
      "cinematic_look": "."
    }}
    /* Add more frames here so that:
       1) frame_id values are consecutive integers starting from 1;
       2) the sum of all duration_s values is exactly 20;
       3) ALL frames use the SAME animation_type (or smooth progression);
       4) Each continuity_note describes how this frame continues from the previous frame's camera position;
       5) All frames are keyframes from ONE continuous camera move. */
  ]
}}
"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        # IMPORTANT: gpt-5.2-chat-latest does not support custom temperature
    )

    return response.choices[0].message.content


def generate_ingredients_plan_json(prompt: str, target_duration_s: int = 15) -> str:
    """
    New architecture: 15s shot-by-shot script + named ingredients.
    - main_script_15s: full shot-by-shot video description (reference for everything).
    - ingredients: list of { name, t2i_prompt } — one lengthy T2I prompt per ingredient.
    - shots: list of shots with detailed_description, movement_prompt, ingredient_names, new_ingredient_names.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not found in .env")

    client = OpenAI(api_key=api_key)
    model = (os.getenv("OPENAI_MODEL") or "gpt-5.2-chat-latest").strip()

    system_prompt = (
        "You are a professional storyboard artist and academic explainer-video designer. "
        "You design shot-by-shot video scripts and extract visual INGREDIENTS (named elements) "
        "with very lengthy, detailed text-to-image prompts for each. "
        "Return ONLY valid JSON. No markdown. No explanations. No extra text."
    )

    user_prompt = f"""
Design a {target_duration_s}-second ACADEMIC EXPLAINER using the INGREDIENTS + SHOTS architecture.

TOPIC:
\"\"\"{prompt}\"\"\"

ARCHITECTURE (follow exactly):
1. MAIN SCRIPT: Write a full shot-by-shot video description for the whole {target_duration_s}s. Each shot MUST include BOTH: (A) Visual description (environment, camera behavior, action, elements, supporting ingredients like arrows/lines) AND (B) Narration (the spoken explanation for that moment, explaining the CONCEPT for university students, not describing what we see). Use a clear structure like: "SHOT N — Title (Approx. t_start–t_end s)\n\nVisuals: ...\n\nNarration: \"...\"". This script is the reference for all generation.
2. INGREDIENTS: From the script, identify only the MAIN VISUAL ELEMENTS that need to be generated as separate images. This includes:
   - PRIMARY OBJECTS: main subjects (e.g., airplane, wing, glass block, water surface, leaf, chloroplast, mirror, laser beam). These MUST be ISOLATED (no background/environment in the image).
   - ENVIRONMENT: background/setting appropriate to the topic (realistic lab, sky, classroom, etc.). This is a SEPARATE ingredient that will be composited with objects later.
   
   CRITICAL: DO NOT create ingredients for supporting visual aids like arrows, dotted lines, labels, or equations. These will be generated directly by the I2V model based on detailed descriptions in the movement_prompt (see below).
   
   Give each ingredient a SHORT NAME (e.g. "airplane", "airplane_wing", "lab_environment"). 
   
   TEXT-TO-IMAGE (T2I) PROMPT RULES — Each ingredient t2i_prompt MUST follow this exact 5-part structure (concatenate into one coherent paragraph):
   - [Scientific Subject]: Be literal and specific. (e.g., "A double-helix DNA strand with clearly visible base pairs", "A flat rectangular plane mirror with sharp edges".)
   - [Action/State]: Describe the physical state. (e.g., "undergoing replication, partially unzipped", "at rest, vertically oriented".)
   - [Style/Medium]: Use academic-grade keywords. (e.g., "Professional scientific illustration, 3D medical render, Octane Render, clean white background, 8k resolution".) For ENVIRONMENT: describe the full background/setting.
   - [Lighting & Texture]: (e.g., "Soft volumetric lighting, translucent materials, realistic glass and protein textures".)
   - [Framing]: (e.g., "Microscopic close-up, shallow depth of field, centered composition", or "ISOLATED on transparent background, no other objects".)
   For PRIMARY OBJECTS: explicitly state ISOLATED on transparent/white/black background. NO environment, NO other objects in frame. For ENVIRONMENT ingredients: use the same 5 parts but describe the full scene.
   LOGIC RULE: If the ingredient is a chart, graph, or data plot, do NOT use t2i_prompt. Instead set "matplotlib_code" to valid Python code that uses Matplotlib (and optionally NumPy) to render the image precisely (e.g., plt.figure(), axes, labels, savefig). Leave t2i_prompt empty or a one-line placeholder when matplotlib_code is set.
3. SHOTS: Each shot has: time_range, duration_s, detailed_description (from main script, including when supporting visual elements like arrows/lines appear/disappear), movement_prompt (for I2V: camera behavior, primary ingredient motion, AND detailed descriptions of supporting visual elements like arrows/lines/labels that the I2V model will generate), ingredient_names (which PRIMARY ingredients appear in this shot - do NOT include supporting elements), new_ingredient_names (primary ingredients introduced ONLY in this shot; shot 1 has all as "new" or list none and put all in ingredient_names), narration_text (must match narration from main_script_15s for this shot), on_screen_text_overlay.

RULES:
- Total duration MUST be exactly {target_duration_s} seconds. Sum of shot duration_s = {target_duration_s}.
- Shot durations MUST vary based on explanation needs:
  * Longer durations (4-6s) for static explanatory holds where narration explains complex concepts or when camera pauses for teaching
  * Medium durations (2-4s) for camera movements, transitions, or moderate complexity
  * Shorter durations (1-2s) for quick transitions or simple visual demonstrations
  * Do NOT make all shots the same duration. Vary them based on what best serves the explanation.
- ingredient_names in each shot must be a subset of the names in ingredients (exact match).
- new_ingredient_names for shot 1: either list all ingredients that appear in shot 1, or leave empty and put them in ingredient_names. For shot 2+: only list ingredients that FIRST APPEAR in this shot.
- NO humans: no people, no faces, no hands. NO logos/watermarks.
- For REAL-WORLD topics use PHOTOREALISTIC descriptions; for ABSTRACT topics use appropriate stylized/digital descriptions.
- I2V movement_prompt (MOTION ONLY): The I2V prompt must NOT re-describe the image. It must focus 100% on MOTION DYNAMICS. Use this formula:
  [Camera Motion] + [Subject Action] + [Environmental Motion].
  - Camera: Use cinematography keywords only: "Slow dolly-in," "Lateral pan left," "Static camera with subject movement," "Smooth orbital rotation," "Subtle push-in," "Hold static."
  - Subject Action: What moves in frame (e.g., "The molecule starts static, then begins to vibrate, and finally splits apart smoothly over 5 seconds."). For supporting elements (arrows, lines): when they appear, move, or disappear.
  - Environmental Motion: Any background or ambient motion (e.g., "No environmental motion," "Particles drift slowly.").
  - Temporal control: Describe the flow explicitly (start → then → end) with timing where helpful.
  - CONSTRAINT: End the movement_prompt with exactly: "Maintain structural integrity and consistency of the source image. No morphing. No hallucinating new objects."
  You may still include detailed start/end positions and paths for primary and supporting elements, but do NOT describe what the image depicts (no re-description of subjects or scene). Only motion.
- CRITICAL FOR SHOT 1: The first shot's first frame will be generated using Image-to-Image (I2I) with Nano Banana Pro, which accepts up to 14 ingredient images. For shot_id=1 ONLY, you MUST provide an `i2i_spatial_prompt` that describes in EXTREME DETAIL:
  * Exact spatial relationships between ALL PRIMARY INGREDIENTS (only the ones listed in ingredient_names): where each object is positioned relative to others (e.g., "mirror is placed above the table", "laser beam originates from the left side and travels horizontally")
  * Camera position and angle: exactly where the camera is and what it's facing (e.g., "camera is positioned directly in front of the scene, facing the objects head-on", "camera is at eye level, looking down at a 30-degree angle")
  * Precise placement: distances, heights, depths, left/right/center positions, foreground/background relationships
  * Lighting and shadows: how light falls on objects, shadows cast by objects, lighting direction relative to camera
  * Scale relationships: relative sizes of objects to each other and to the frame
  * Any spatial interactions: objects touching, overlapping, or positioned with specific gaps
  NOTE: Do NOT include supporting visual elements (arrows, lines, labels) in the i2i_spatial_prompt - these will be generated by I2V later based on the movement_prompt. Only describe the PRIMARY INGREDIENTS and ENVIRONMENT.
  This prompt will be used with the isolated ingredient images to generate the first frame via I2I. For shots 2+, leave i2i_spatial_prompt empty (they use I2V from previous last frame).

STYLIST: The style_bible must include "style_suffix": a short phrase appended to every t2i_prompt for visual consistency (e.g., "muted professional teal and grey palette, 4k, cinematic"). The pipeline will append it automatically; you only need to define it once here.

OUTPUT JSON (must match exactly):
{{
  "main_script_15s": "Full shot-by-shot description of the entire {target_duration_s}s video. Each shot MUST include BOTH visual description AND narration. Use structure: SHOT N — Title (Approx. t_start–t_end s)\n\nVisuals: ...\n\nNarration: \"...\"",
  "style_bible": {{
    "visual_style": "Professional, sophisticated, cinematic. Documentary/science channel. Photorealistic for real-world topics.",
    "camera_rules": "One continuous camera move across all shots. No cuts.",
    "lighting_rules": "Professional, clear, well-lit.",
    "continuity_rules": "Same continuous shot. Elements consistent across shots.",
    "style_suffix": "Muted professional teal and grey palette, 4k, cinematic. Academic scientific visualization."
  }},
  "ingredients": [
    {{
      "name": "short_name_no_spaces",
      "t2i_prompt": "[Scientific Subject] A flat plane mirror with sharp edges. [Action/State] At rest, vertically oriented. [Style/Medium] Professional scientific illustration, clean white background, 8k resolution, ISOLATED on transparent background. [Lighting & Texture] Soft key light, subtle specular highlight. [Framing] Centered, no other objects.",
      "matplotlib_code": null
    }}
  ],
  "shots": [
    {{
      "shot_id": 1,
      "time_range": "0-4s",
      "duration_s": 4,
      "detailed_description": "Very detailed description of what happens in this shot (visuals + when supporting ingredients appear/disappear).",
      "movement_prompt": "Slow dolly-in. Laser beam travels left to right toward mirror; mirror and environment static. No environmental motion. Over 4 seconds: beam advances to mirror surface. Maintain structural integrity and consistency of the source image. No morphing. No hallucinating new objects.",
      "ingredient_names": ["name1", "name2"],
      "new_ingredient_names": [],
      "narration_text": "Narration explaining the concept for this shot (from main_script_15s).",
      "on_screen_text_overlay": "none",
      "i2i_spatial_prompt": "EXTREMELY DETAILED description of spatial relationships for I2I: exact positions of all ingredients relative to each other and camera, camera position/angle (e.g., 'camera facing directly at scene', 'mirror placed above table'), precise placement, lighting, shadows, scale relationships. Only for shot 1."
    }},
    {{
      "shot_id": 2,
      "time_range": "4-7s",
      "duration_s": 3,
      "detailed_description": "Very detailed description of what happens in this shot.",
      "movement_prompt": "Static camera with subject movement. Normal line and angle arcs fade in at point of incidence; laser and mirror unchanged. Maintain structural integrity and consistency of the source image. No morphing. No hallucinating new objects.",
      "ingredient_names": ["name1", "name3"],
      "new_ingredient_names": ["name3"],
      "narration_text": "Narration explaining the concept for this shot.",
      "on_screen_text_overlay": "none",
      "i2i_spatial_prompt": ""
    }}
  ]
}}
Use 3–6 shots with VARIED durations (not all the same). Sum of duration_s = {target_duration_s}. All ingredient names in shots must exist in ingredients. The narration_text in each shot should match the narration written in main_script_15s for that shot.
"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    return response.choices[0].message.content


def generate_audio_revision_json(main_script_15s: str, shots: list) -> str:
    """
    Revise voiceover and plan sound design for the full video based on the main script.
    Returns JSON with:
      - revised_narration: [ { shot_id, revised_text }, ... ]
      - sound_design: [ { shot_id, start_s, end_s, description }, ... ]
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not found in .env")

    client = OpenAI(api_key=api_key)
    model = (os.getenv("OPENAI_MODEL") or "gpt-4o").strip()

    shots_summary = []
    t = 0
    for s in shots:
        shot_id = s.get("shot_id")
        dur = int(s.get("duration_s", 3))
        shots_summary.append({
            "shot_id": shot_id,
            "time_range": f"{t}-{t + dur}s",
            "duration_s": dur,
            "current_narration": (s.get("narration_text") or "").strip(),
            "visual_description": (s.get("detailed_description") or "").strip(),
        })
        t += dur

    system_prompt = (
        "You are a professional video editor and sound designer for academic explainer videos. "
        "You revise voiceover for clarity and coherence, and you plan ambient/sound-design that matches what is happening on screen. "
        "Return ONLY valid JSON. No markdown. No explanations."
    )
    user_prompt = f"""
Given the MAIN SCRIPT and the current shot-by-shot plan, output two things:

1. REVISED NARRATION: For each shot, provide improved voiceover text that explains the content clearly and matches the main script. Keep similar length (about 2.5-3 words per second). Make the full narration flow as one coherent explanation.

2. SOUND DESIGN: For each shot, describe the SOUNDS that should be heard while that part of the video plays (ambient, Foley, or abstract). Examples: "gentle wind, leaves rustling", "soft whoosh, subtle sci-fi hum", "quiet indoor ambience", "nature sounds, birds distant". One short phrase per shot.

MAIN SCRIPT (full video description):
\"\"\"{main_script_15s}\"\"\"

SHOTS (with current narration and visual description):
{json.dumps(shots_summary, indent=2)}

Output JSON exactly in this form (no extra keys):
{{
  "revised_narration": [
    {{ "shot_id": 1, "revised_text": "Revised voiceover for this shot." }},
    ...
  ],
  "sound_design": [
    {{ "shot_id": 1, "start_s": 0, "end_s": 3, "description": "gentle wind, leaves rustling" }},
    ...
  ]
}}
- revised_narration: one entry per shot, same shot_ids as input. revised_text = the new voiceover for that shot.
- sound_design: one entry per shot. start_s and end_s = start/end time in seconds (cumulative). description = short phrase for what sounds to play during that segment.
"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    return response.choices[0].message.content


# Backward-compatible alias (optional)
def generate_scene_plan_json(prompt: str, target_duration_s: int) -> str:
    return generate_clip_plan_json(prompt, target_duration_s)
