"""
Stitching pipeline (3 steps):
1. Stitch clip videos into one big video (no audio).
2. Send stitched video + original script to Gemini; Gemini analyzes the video and writes
   a detailed prompt/spec for ElevenLabs (narration + SFX with timing and delivery).
3. Generate audio from that spec (ElevenLabs) and mux with the stitched video → final_video.mp4.
"""
from pathlib import Path
import subprocess
import sys

from video_actions import _ffmpeg_exe


def stitch_clips(project_dir: Path, run_audio_pipeline: bool = True) -> Path:
    clips_dir = project_dir / "clips"
    output_video = project_dir / "final_video.mp4"

    clips = sorted(clips_dir.glob("clip_*.mp4"))
    if not clips:
        raise RuntimeError("No clips found to stitch.")

    print(f"Found {len(clips)} clips to stitch.")
    ffmpeg_path = _ffmpeg_exe()

    # Step 1: Stitch clips into one big video (no audio)
    video_list_file = clips_dir / "clips.txt"
    with video_list_file.open("w", encoding="utf-8") as f:
        for clip in clips:
            p = str(clip.resolve()).replace("'", r"'\''")
            f.write(f"file '{p}'\n")

    temp_video = project_dir / "temp_stitched_no_audio.mp4"
    cmd_video = [
        str(ffmpeg_path),
        "-y",
        "-f", "concat",
        "-safe", "0",
        "-i", str(video_list_file),
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-r", "30",
        str(temp_video),
    ]
    try:
        subprocess.run(cmd_video, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError as e:
        if video_list_file.exists():
            video_list_file.unlink()
        raise RuntimeError(f"Failed to combine video clips: {e}")

    if video_list_file.exists():
        video_list_file.unlink()

    print("[STEP 1] Stitched video (no audio) saved.")

    if not run_audio_pipeline:
        temp_video.rename(output_video)
        print(f"[OK] Final video (no audio): {output_video}")
        return output_video

    # Prefer main narration script audio (from planner) as the only track for the final video
    narration_script_audio = project_dir / "audio" / "narration_script_audio.mp3"
    if narration_script_audio.exists():
        combined_audio = narration_script_audio
        print("[AUDIO] Using main narration script audio (from planning) for final video.")
    else:
        # Step 2 + 3: Gemini analyzes video + script → ElevenLabs audio
        try:
            from stitch_audio_gemini import analyze_video_and_generate_audio
            combined_audio = analyze_video_and_generate_audio(project_dir, temp_video)
        except Exception as e:
            print(f"[WARN] Audio pipeline failed: {e}")
            print("   Saving final video without audio.")
            temp_video.rename(output_video)
            if temp_video.exists():
                temp_video.unlink(missing_ok=True)
            return output_video

    # Step 3 (mux): Combine stitched video + combined audio → final_video.mp4
    cmd_final = [
        str(ffmpeg_path),
        "-y",
        "-i", str(temp_video),
        "-i", str(combined_audio),
        "-c:v", "copy",
        "-c:a", "aac",
        "-b:a", "128k",
        "-shortest",
        str(output_video),
    ]
    try:
        subprocess.run(cmd_final, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print(f"[OK] Final video with audio: {output_video}")
    except subprocess.CalledProcessError:
        cmd_final_reencode = [
            str(ffmpeg_path),
            "-y",
            "-i", str(temp_video),
            "-i", str(combined_audio),
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac",
            "-b:a", "128k",
            "-shortest",
            str(output_video),
        ]
        subprocess.run(cmd_final_reencode, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print(f"[OK] Final video with audio (re-encoded): {output_video}")

    if temp_video.exists():
        temp_video.unlink(missing_ok=True)
    # Only remove combined_audio if it was generated by the pipeline (temp file), not the project's narration script
    if combined_audio.exists() and combined_audio.resolve() != narration_script_audio.resolve():
        combined_audio.unlink(missing_ok=True)

    return output_video


if __name__ == "__main__":
    run_audio = True
    args = [a for a in sys.argv[1:] if a != "--no-audio"]
    if "--no-audio" in sys.argv:
        run_audio = False
    if len(args) >= 1:
        project_path = Path(args[0])
    else:
        project_path = Path(
            input("Project folder path (e.g. projects/7dad8d32): ").strip()
        )
    stitch_clips(project_path, run_audio_pipeline=run_audio)
